# Generated by Django 4.2.3 on 2023-09-08 12:51

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contac',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha modificacion')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellido')),
                ('document', models.IntegerField(blank=True, null=True, verbose_name='Documento de Identidad')),
                ('addres', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
    ]
