# Generated by Django 4.2.3 on 2023-09-11 15:05

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_delete_contac'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='addres',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(max_length=254, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=254, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Telefono'),
        ),
    ]
