# Generated by Django 4.2.3 on 2023-09-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Fecha modificacion')),
                ('to', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(max_length=254, verbose_name='Destinatario')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('response', models.TextField(verbose_name='Respuesta')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
