# Generated by Django 4.2.3 on 2023-09-29 14:55

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emaillog',
            options={'verbose_name': 'Registro de email', 'verbose_name_plural': 'Registro de emails'},
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
