# Generated by Django 4.2.3 on 2023-09-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_emaillog_options_alter_emaillog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='content',
            field=models.TextField(verbose_name='Contenido'),
        ),
    ]
