# Generated by Django 4.2.3 on 2023-09-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saledetail',
            options={'verbose_name': 'Detalle', 'verbose_name_plural': 'Detalle'},
        ),
        migrations.AddField(
            model_name='sale',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='price',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=12),
        ),
    ]
