# Generated by Django 4.2.3 on 2023-09-07 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_alter_saledetail_options_sale_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'permissions': [('export_sale', 'Can export sale')], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
    ]
