# Generated by Django 4.2.3 on 2023-09-11 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_email_alter_contact_addres_and_more'),
        ('sale', '0003_alter_sale_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_sales', to='contact.contact', verbose_name='Cliente'),
        ),
    ]
